---
title: "World's Most Productive Metro Areas, by GDP (PPP)"
date: "August 3, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load_libs}
library(XML)
library(leaflet)
library(stringr)
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(httr))
```

```{r get_html_and_parse}
url <- "https://en.wikipedia.org/wiki/List_of_cities_by_GDP"
download.file(url,"data.html")
ht <- htmlParse("data.html")
unlink("data.html")
```

```{r process}
dat <- xpathSApply(ht,"//table/tbody/tr/td",xmlValue)[1:140]
dat <- sub("\n","",dat)
dat <- str_trim(dat)
df <- as.data.frame(matrix(dat, nrow=20, ncol=7, byrow=TRUE))
names(df) <- c("rank_nom","rank_ppp","metro_area","country","unsd_sub_region","gdp_usdb","gdp_ppp_usdb")

df$gdp_ppp_usdb <- sub(",","",df$gdp_ppp_usdb)
df$gdp_ppp_usdb <- sub(",",".",df$gdp_ppp_usdb)
df$gdp_ppp_usdb <- as.numeric(df$gdp_ppp_usdb)
df$rank_ppp <- as.integer(df$rank_ppp)

df <- df %>% select(rank_ppp:country,gdp_ppp_usdb)
```

```{r lat_long_api, cache=TRUE}
## Get lat, long coordinates of city from Google Maps Geocoding API
get_coordinates <- function(city){
    key <- "AIzaSyCIkAZR2obEeO6aepnBgiUr1i_qOhLhYDo"
    req_url_1 <- "https://maps.googleapis.com/maps/api/geocode/xml?address="
    req_url_2 <- paste0("&key=", key)
    city <- gsub(" ","%20", city)
    req_url <- paste0(req_url_1, city, req_url_2)
    
    cxml <- xmlParse(GET(req_url))
    lat <- xpathSApply(cxml, "//location/lat", xmlValue)
    long <- xpathSApply(cxml, "//location/lng", xmlValue)
    
    c(lat, long)
}

coords <- matrix(unlist(lapply(df$metro_area, get_coordinates)), nrow=20, ncol=2, byrow=TRUE)
coords_df <- as.data.frame(coords)
names(coords_df) <- c("latitude","longitude")
df <- cbind(df, coords_df)
df <- df %>% mutate(
    latitude = as.numeric(latitude),
    longitude = as.numeric(longitude),
    circle_weight = gdp_ppp_usdb/max(gdp_ppp_usdb)*50
)
```

```{r generate_map}
my_map <- leaflet(df) %>% 
    addTiles() %>% 
    addCircles(lat = ~latitude, lng = ~longitude, weight = ~circle_weight,
               label = paste0(df$metro_area,", ",df$country), 
               popup = paste0(df$metro_area,", ",df$country, "<br>",
                              "World Rank: ", df$rank_ppp, "<br>",
                              "GDP (PPP): $", df$gdp_ppp_usdb, "B"))
my_map
```

## Methods
First, the top 20 metropolitan areas and GDP (PPP) data were scraped from [this Wikipedia page](`r url`). Then, Google's Geocoding API was used to obtain coordinates for each of the 20 metro areas. The collected data is reproduced in the map above. Data was originally collected/estimated by Visual Capitalist in 2021.
